"""initial schema

Hand-written (not autogenerated) initial migration creating every table
described in the PRD plus the two additions this implementation makes:
`outbox_events` (Bonus C) and `dead_letter_orders` (Bonus B).

Revision ID: 0001
Revises:
Create Date: 2026-01-01
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- users ---------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "CLIENT", name="user_role"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ---- products --------------------------------------------------------
    op.create_table(
        "products",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("sku", sa.String(64), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("price", sa.Numeric(12, 2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_products_sku", "products", ["sku"], unique=True)

    # ---- warehouses --------------------------------------------------------
    op.create_table(
        "warehouses",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("location", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---- inventory -----------------------------------------------------
    # The two CHECK constraints are the database-level backstop for the
    # PRD's "inventory must never become negative" rule.
    op.create_table(
        "inventory",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("product_id", sa.String(64), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("warehouse_id", sa.String(64), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("available_quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("reserved_quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("product_id", "warehouse_id", name="uq_inventory_product_warehouse"),
        sa.CheckConstraint("available_quantity >= 0", name="ck_inventory_available_nonnegative"),
        sa.CheckConstraint("reserved_quantity >= 0", name="ck_inventory_reserved_nonnegative"),
    )
    op.create_index("ix_inventory_product_id", "inventory", ["product_id"])
    op.create_index("ix_inventory_warehouse_id", "inventory", ["warehouse_id"])

    # ---- orders -----------------------------------------------------------
    op.create_table(
        "orders",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RESERVED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", "EXPIRED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(12, 2), nullable=False),
        sa.Column("created_by_user_id", sa.String(64), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("payment_token", sa.String(32), nullable=False, server_default="success"),
        sa.Column("processing_attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("idempotency_key", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_orders_status", "orders", ["status"])
    op.create_index("ix_orders_created_at", "orders", ["created_at"])
    op.create_index("ix_orders_created_by_user_id", "orders", ["created_by_user_id"])
    op.create_index("ix_orders_idempotency_key", "orders", ["idempotency_key"], unique=True)

    # ---- order_items --------------------------------------------------
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("order_id", sa.String(64), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("product_id", sa.String(64), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("warehouse_id", sa.String(64), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False),
        sa.Column("unit_price", sa.Numeric(12, 2), nullable=False),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"])
    op.create_index("ix_order_items_product_id", "order_items", ["product_id"])

    # ---- inventory_reservations --------------------------------------
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("order_id", sa.String(64), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("product_id", sa.String(64), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("warehouse_id", sa.String(64), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RELEASED", "CONSUMED", name="reservation_status"),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_inventory_reservations_order_id", "inventory_reservations", ["order_id"])
    # Composite-purpose index: the expiration scheduler scans exactly this
    # (status, expires_at) shape (WHERE status = 'ACTIVE' AND expires_at < now()).
    op.create_index("ix_inventory_reservations_status", "inventory_reservations", ["status"])
    op.create_index("ix_inventory_reservations_expires_at", "inventory_reservations", ["expires_at"])

    # ---- inventory_audit_logs ------------------------------------------
    op.create_table(
        "inventory_audit_logs",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("product_id", sa.String(64), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("warehouse_id", sa.String(64), sa.ForeignKey("warehouses.id"), nullable=False),
        sa.Column("change", sa.Integer, nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "STOCK_ADDED", "STOCK_REMOVED", "INVENTORY_RESERVED", "RESERVATION_RELEASED",
                "ORDER_COMPLETED", "MANUAL_ADJUSTMENT", name="audit_event_type",
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.String(64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_inventory_audit_logs_product_id", "inventory_audit_logs", ["product_id"])
    op.create_index("ix_inventory_audit_logs_reference_id", "inventory_audit_logs", ["reference_id"])
    op.create_index("ix_inventory_audit_logs_created_at", "inventory_audit_logs", ["created_at"])

    # ---- idempotency_keys ------------------------------------------------
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(255), primary_key=True),
        sa.Column("request_hash", sa.String(64), nullable=False),
        sa.Column("order_id", sa.String(64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", name="idempotency_status"),
            nullable=False,
            server_default="IN_PROGRESS",
        ),
        sa.Column("response_body", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ---- outbox_events (Bonus C) -----------------------------------------
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("aggregate_type", sa.String(32), nullable=False),
        sa.Column("aggregate_id", sa.String(64), nullable=False),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PUBLISHED", name="outbox_status"),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_outbox_events_aggregate_id", "outbox_events", ["aggregate_id"])
    op.create_index("ix_outbox_events_status", "outbox_events", ["status"])

    # ---- dead_letter_orders (Bonus B) -------------------------------------
    op.create_table(
        "dead_letter_orders",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("order_id", sa.String(64), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column("attempts", sa.Integer, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_dead_letter_orders_order_id", "dead_letter_orders", ["order_id"])


def downgrade() -> None:
    op.drop_table("dead_letter_orders")
    op.drop_table("outbox_events")
    op.drop_table("idempotency_keys")
    op.drop_table("inventory_audit_logs")
    op.drop_table("inventory_reservations")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("inventory")
    op.drop_table("warehouses")
    op.drop_table("products")
    op.drop_table("users")

    # Explicitly drop the Postgres ENUM types (Postgres does not drop them
    # automatically just because the columns using them were dropped).
    for enum_name in (
        "order_status",
        "reservation_status",
        "audit_event_type",
        "idempotency_status",
        "outbox_status",
        "user_role",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
